weapons_and_traits <- [
	"hsdm_traits/hsdm_trait.nut",
	"hsdm_traits/weapon_crit_manager.nut",
	"hsdm_traits/blast_jumping_debuff_hack.nut"
	"hsdm_traits/gain_clip_on_hit.nut",
	"hsdm_traits/overfill_on_ammo_pickup.nut"

	"hsdm_traits/scout_on_attach_detach.nut",
	"hsdm_traits/sniper_on_attach_detach.nut",
	"hsdm_traits/heavy_on_attach_detach.nut",

	"hsdm_weapons/weapon_helpers.nut",
	"hsdm_weapons/melee_helpers.nut",

	"hsdm_weapons/single_class/scout/scout_stock_melee.nut",
	"hsdm_weapons/single_class/scout/scattergun.nut",
	"hsdm_weapons/single_class/scout/shortstop.nut",
	"hsdm_weapons/single_class/scout/soda_popper.nut"
	"hsdm_weapons/single_class/scout/force_a_nature.nut"
	"hsdm_weapons/single_class/scout/back_scatter.nut"
	"hsdm_weapons/single_class/scout/baby_faces_blaster.nut"
	"hsdm_weapons/single_class/scout/bonk_atomic_punch.nut",
	"hsdm_weapons/single_class/scout/crit_a_cola.nut",
	"hsdm_weapons/single_class/scout/mad_milk.nut",
	"hsdm_weapons/single_class/scout/winger.nut",
	"hsdm_weapons/single_class/scout/pretty_boys_pocket_pistol.nut",
	"hsdm_weapons/single_class/scout/flying_guillotine.nut",
	"hsdm_weapons/single_class/scout/bat.nut",
	"hsdm_weapons/single_class/scout/candy_cane.nut",
	"hsdm_weapons/single_class/scout/boston_basher.nut",
	"hsdm_weapons/single_class/scout/sandman.nut",
	"hsdm_weapons/single_class/scout/sun_on_a_stick.nut",
	"hsdm_weapons/single_class/scout/fan_o_war.nut",
	"hsdm_weapons/single_class/scout/atomizer.nut",

	"hsdm_weapons/single_class/soldier/soldier_stock_melee.nut",
	"hsdm_weapons/single_class/soldier/rocket_launcher.nut",
	"hsdm_weapons/single_class/soldier/black_box.nut",
	"hsdm_weapons/single_class/soldier/rocket_jumper.nut",
	"hsdm_weapons/single_class/soldier/liberty_launcher.nut",
	"hsdm_weapons/single_class/soldier/beggars_bazooka.nut",
	"hsdm_weapons/single_class/soldier/cow_mangler.nut",
	"hsdm_weapons/single_class/soldier/direct_hit.nut",
	"hsdm_weapons/single_class/soldier/air_strike.nut",
	"hsdm_weapons/single_class/soldier/buff_banner.nut",
	"hsdm_weapons/single_class/soldier/battalions_backup.nut",
	"hsdm_weapons/single_class/soldier/concheror.nut",
	"hsdm_weapons/single_class/soldier/gunboats.nut",
	"hsdm_weapons/single_class/soldier/mantreads.nut",
	"hsdm_weapons/single_class/soldier/righteous_bison.nut",
	"hsdm_weapons/single_class/soldier/shovel.nut",
	"hsdm_weapons/single_class/soldier/equalizer.nut",
	"hsdm_weapons/single_class/soldier/pain_train.nut",
	"hsdm_weapons/single_class/soldier/market_gardener.nut",
	"hsdm_weapons/single_class/soldier/disciplinary_action.nut",
	"hsdm_weapons/single_class/soldier/escape_plan.nut",

	"hsdm_weapons/single_class/pyro/pyro_stock_melee.nut",
	"hsdm_weapons/single_class/pyro/flamethrower.nut",
	"hsdm_weapons/single_class/pyro/backburner.nut",
	"hsdm_weapons/single_class/pyro/degreaser.nut",
	"hsdm_weapons/single_class/pyro/phlogistinator.nut",
	"hsdm_weapons/single_class/pyro/dragons_fury.nut",
	"hsdm_weapons/single_class/pyro/flaregun.nut",
	"hsdm_weapons/single_class/pyro/detonator.nut",
	"hsdm_weapons/single_class/pyro/scorch_shot.nut",
	"hsdm_weapons/single_class/pyro/manmelter.nut",
	"hsdm_weapons/single_class/pyro/thermal_thruster.nut",
	"hsdm_weapons/single_class/pyro/fireaxe.nut",
	"hsdm_weapons/single_class/pyro/axtinguisher.nut",
	"hsdm_weapons/single_class/pyro/homewrecker.nut",
	"hsdm_weapons/single_class/pyro/powerjack.nut",
	"hsdm_weapons/single_class/pyro/back_scratcher.nut",
	"hsdm_weapons/single_class/pyro/sharpened_volcano_fragment.nut",
	"hsdm_weapons/single_class/pyro/third_degree.nut",
	"hsdm_weapons/single_class/pyro/neon_annihilator.nut",
	"hsdm_weapons/single_class/pyro/hot_hand.nut",

	"hsdm_weapons/single_class/engie/engie_stock_melee.nut",
	"hsdm_weapons/single_class/engie/widowmaker.nut",

	"hsdm_weapons/single_class/demo/demo_stock_melee.nut",
	"hsdm_weapons/single_class/demo/grenade_launcher.nut",
	"hsdm_weapons/single_class/demo/loch_n_load.nut",
	"hsdm_weapons/single_class/demo/iron_bomber.nut",
	"hsdm_weapons/single_class/demo/loose_cannon.nut",
	"hsdm_weapons/single_class/demo/sticky_launcher.nut",
	"hsdm_weapons/single_class/demo/scottish_resistance.nut",
	"hsdm_weapons/single_class/demo/sticky_jumper.nut",
	"hsdm_weapons/single_class/demo/quickiebomb_launcher.nut",
	"hsdm_weapons/single_class/demo/booties.nut",
	"hsdm_weapons/single_class/demo/chargin_targe.nut",
	"hsdm_weapons/single_class/demo/splendid_screen.nut",
	"hsdm_weapons/single_class/demo/tide_turner.nut",
	"hsdm_weapons/single_class/demo/bottle.nut",
	"hsdm_weapons/single_class/demo/eyelander.nut",
	"hsdm_weapons/single_class/demo/scotsmans_skullcutter.nut",
	"hsdm_weapons/single_class/demo/claidheamh_mor.nut",
	"hsdm_weapons/single_class/demo/persian_persuader.nut",
	"hsdm_weapons/single_class/demo/ullapool_caber.nut",

	"hsdm_weapons/single_class/heavy/heavy_stock_melee.nut",
	"hsdm_weapons/single_class/heavy/minigun.nut",
	"hsdm_weapons/single_class/heavy/natascha.nut",
	"hsdm_weapons/single_class/heavy/brass_beast.nut",
	"hsdm_weapons/single_class/heavy/tomislav.nut",
	"hsdm_weapons/single_class/heavy/huo_long_heater.nut",
	"hsdm_weapons/single_class/heavy/family_business.nut",
	"hsdm_weapons/single_class/heavy/sandvich.nut",
	"hsdm_weapons/single_class/heavy/dalokohs_bar.nut",
	"hsdm_weapons/single_class/heavy/buffalo_steak_sandvich.nut",
	"hsdm_weapons/single_class/heavy/second_banana.nut",
	"hsdm_weapons/single_class/heavy/fists.nut",
	"hsdm_weapons/single_class/heavy/kgb.nut",
	"hsdm_weapons/single_class/heavy/gru.nut",
	"hsdm_weapons/single_class/heavy/warriors_spirit.nut",
	"hsdm_weapons/single_class/heavy/fists_of_steel.nut",
	"hsdm_weapons/single_class/heavy/eviction_notice.nut",
	"hsdm_weapons/single_class/heavy/holiday_punch.nut",

	"hsdm_weapons/single_class/medic/medic_stock_melee.nut",

	"hsdm_weapons/single_class/sniper/sniper_stock_melee.nut",
	"hsdm_weapons/single_class/sniper/shahanshah.nut",

	"hsdm_weapons/single_class/spy/spy_stock_melee.nut",

	"hsdm_weapons/multi_class/grapplehook.nut",
	"hsdm_weapons/multi_class/base_jumper.nut",
	"hsdm_weapons/multi_class/shotgun.nut",
	"hsdm_weapons/multi_class/panic_attack.nut",
	"hsdm_weapons/multi_class/reserve_shooter.nut",
	"hsdm_weapons/multi_class/pistol.nut",
	"hsdm_weapons/multi_class/half_zatoichi.nut",
]

foreach (file in weapons_and_traits)
	Include(file)